### ISSUE TITLE
Shipping cost and Discount properties

### ISSUE THREAD

**Issue by FrancescoTalotta** [TDKorn/my-magento#10]
Hello,

is there any command to get the shipping cost, the discount and the Grand Total from an invoice? 

Thank you

Francesco

**Comment by TDKorn** [comment]
Hey @FrancescoTalotta,

Yes, this information is available in the attributes of an `Invoice` object. You can retrieve an `Invoice` using an [```InvoiceSearch```](https://my-magento.readthedocs.io/en/latest/search_module.html#magento.search.InvoiceSearch). 

The specific attributes you'd be looking for are:
- Shipping Cost:  `shipping_amount`/`shipping_incl_tax`
- Discount: `discount_amount`
- Grand Total: `grand_total`

See here for a full list of fields returned by the API: https://adobe-commerce.redoc.ly/2.4.6-admin/tag/invoicesid#operation/GetV1InvoicesId
